 
name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unitTests:
    strategy:
      matrix:
        name: [ubuntu-gcc, ubuntu-clang, windows-VS]
        include:
            - name: ubuntu-gcc
              os: ubuntu-latest
              compiler_opt: "-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -G \"Unix Makefiles\""
            - name: ubuntu-clang
              os: ubuntu-latest
              compiler_opt: "-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -G \"Unix Makefiles\""
            - name: windows-VS
              os: windows-latest
              compiler_opt: ""

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Checkout submodules
      run:  git submodule update --init --recursive
    - name: CMake configure
      run:  cmake -B./build -DCMAKE_INSTALL_PREFIX:STRING=./artifacts/ -DBUILD_SAMPLES=OFF -DBUILD_TESTS=ON -DCMAKE_CONFIGURATION_TYPES="Release" -DCMAKE_BUILD_TYPE:STRING=Release ${{ matrix.compiler_opt }}     
    - name: Build
      run:  cmake --build ./build --config Release
    - name: Install
      run:  cmake --install ./build --config Release
    - name: Test-01
      run: ./artifacts/bin/Test01-Range
    - name: Test-02
      run: ./artifacts/bin/Test02-Distribution
    - name: Test-03
      run: ./artifacts/bin/Test03-DistributionFinder
    - name: Test-04
      run: ./artifacts/bin/Test04-FactorSetting
    - name: Test-05
      run: ./artifacts/bin/Test05-FactorConstruction
    - name: Test-06
      run: ./artifacts/bin/Test06-Insertions
    - name: Test-07
      run: ./artifacts/bin/Test07-Evidences
    - name: Test-08
      run: ./artifacts/bin/Test08-BeliefPropagation
    - name: Test-09
      run: ./artifacts/bin/Test09-Gibbs
    - name: Test-10
      run: ./artifacts/bin/Test10-Learning
    - name: Test-11
      run: ./artifacts/bin/Test11-ThreadPoolEfficiency
    - uses: actions/upload-artifact@v2
      with:
        path: artifacts
        name: ${{ matrix.name }}
