 
name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unitTests:
    strategy:
      matrix:
        name: [ubuntu-gcc, ubuntu-clang, windows-VS]
        include:
            - name: ubuntu-gcc
              os: ubuntu-latest
              compiler_opt: "-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -G \"Unix Makefiles\" -DBUILD_EFG_COMPILER_CHECK=ON"
            - name: ubuntu-clang
              os: ubuntu-latest
              compiler_opt: "-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -G \"Unix Makefiles\" -DBUILD_EFG_COMPILER_CHECK=ON"
            - name: windows-VS
              os: windows-latest
              compiler_opt: ""

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Checkout submodules
      run:  git submodule update --init --recursive
    - name: CMake configure
      run:  cmake -B./build -DCMAKE_INSTALL_PREFIX:STRING=./artifacts/ -DBUILD_EFG_SAMPLES=OFF -DBUILD_EFG_TESTS=ON -DCMAKE_CONFIGURATION_TYPES="Release" -DCMAKE_BUILD_TYPE:STRING=Release ${{ matrix.compiler_opt }}     
    - name: Build
      run:  cmake --build ./build --config Release
    - name: Install
      run:  cmake --install ./build --config Release
    - name: Tests
      run: ./artifacts/bin/Tests "[range]"
    - name: Tests
      run: ./artifacts/bin/Tests "[distribution]"
    - name: Tests
      run: ./artifacts/bin/Tests "[factor]"
    - name: Tests
      run: ./artifacts/bin/Tests "[factor-special]"
    - name: Tests
      run: ./artifacts/bin/Tests "[insertion]"
    - name: Tests
      run: ./artifacts/bin/Tests "[evidence]"
    - name: Tests
      run: ./artifacts/bin/Tests "[io]"
    - name: Tests
      run: ./artifacts/bin/Tests "[propagation]"
    - name: Tests
      run: ./artifacts/bin/Tests "[pool]"
    - name: Tests
      run: ./artifacts/bin/Tests "[gibbs_sampling]"
    - name: Tests
      run: ./artifacts/bin/Tests "[gradient]"
    - name: Tests
      run: ./artifacts/bin/Tests "[train]"
    - uses: actions/upload-artifact@v2
      with:
        path: artifacts
        name: ${{ matrix.name }}
